### PR TITLE
GUI.py

### PR DESCRIPTION
**Pull request by AndrewArstall**
This uses the pathlib package to find the output data file and set it to be a JSON file (i think).

### CODE REVIEW

**Comment by martinstarkov** [comment]
Can you elaborate on what you mean by setting it to be a JSON file?

We need the user to select a file and that file will be stored in and read from a json file, for example:
User opens file browser, selects the file “C:/Desktop/VelocityCMM.dat”, this string is then saved to a json file under the variable “velocity_field_path” and then my code should be able to go
path = json_file[“velocity_field_path”]
(path is now “C:/Desktop/…”)

**Comment by AndrewArstall** [comment]
I think it does exactly what you said. The path of this velocityfield.dat is saved to a variable known as file_path which is then added to the JSON dictionary on line 99. The path of the file can also be retrieved by calling the function, file_locator() which returns the path of the velocityfield.dat file.

**Comment by martinstarkov** [comment]
Why is velocityfield.dat hardcoded though? It should be a variable selected through the file explorer which could have any name.

**Comment by AndrewArstall** [comment]
Is it necessary to have it that way? The current code produces a file known as velocityfield.dat which is identical to the velocity field that can be selected. That way, the data can be acquired with the path known but whilst the name of the selected file is different from velocityfield.dat, the user will not see any major difference. If it is necessary to know the path of the selected file, why is that the case?

**Pull request closed without merging**
